
| Parameter |Description| Content type |
|---|----|---|
|age| Age in years| integer |
|gender| Male or Female|integer (1 or 2)|
| bmi | Body mass index | float |
|no_of_children| Number of children | integer|
|smoker| Whether smoker or not | integer (0 or 1)|
|region| Which US region - NW, NE, SW, SE | integer (1,2,3 or 4 respectively)| 
|charges| Annual Insurance charges in USD | float|

## Objectives 
In this project, you will:
 - Load the data as a `pandas` dataframe
 - Clean the data, taking care of the blank entries
 - Run exploratory data analysis (EDA) and identify the attributes that most affect the `charges`
 - Develop single variable and multi variable Linear Regression models for predicting the `charges`
 - Use Ridge regression to refine the performance of Linear regression models.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests

In [2]:
def download (url, fileName):
    response = requests.get(url)
    if(response.status_code == 200):
        with open(fileName, "wb") as f:
            f.write(response.content)

In [3]:
filepath = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/medical_insurance_dataset.csv'
file_name = 'medical_data.csv'

In [4]:
download (filepath, file_name)

In [5]:
df = pd.read_csv(file_name)
df.head()

   19  1    27.9  0 1.1  3    16884.924
0  18  2  33.770  1   0  4   1725.55230
1  28  2  33.000  3   0  4   4449.46200
2  33  2  22.705  0   0  1  21984.47061
3  32  2  28.880  0   0  1   3866.85520
4  31  1  25.740  0   ?  4   3756.62160

In [6]:
headers = ["age", "gender", "bmi", "no_of_children", "smoker", "region", "charges"]
df.columns = headers

In [7]:
df.head()

  age  gender     bmi  no_of_children smoker  region      charges
0  18       2  33.770               1      0       4   1725.55230
1  28       2  33.000               3      0       4   4449.46200
2  33       2  22.705               0      0       1  21984.47061
3  32       2  28.880               0      0       1   3866.85520
4  31       1  25.740               0      ?       4   3756.62160

# Task 2 : Data Wrangling

In [8]:
# Use `dataframe.info()` to identify the columns that have some 'Null' (or NaN) information.
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2771 entries, 0 to 2770
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             2771 non-null   str
 1   gender          2771 non-null   int64
 2   bmi             2771 non-null   float64
 3   no_of_children  2771 non-null   int64
 4   smoker          2771 non-null   str
 5   region          2771 non-null   int64
 6   charges         2771 non-null   float64
dtypes: float64(2), int64(3), str(2)
memory usage: 151.7 KB

In [14]:
df = df.replace('?', np.nan)
df.isnull().sum()

age               4
gender            0
bmi               0
no_of_children    0
smoker            7
region            0
charges           0
dtype: int64

In [22]:
# update the NaN value of age and smoker by their mean value and most frequency value with respectively.

#Calculate mean of the age
age_mean = df["age"].astype("float").mean(axis= 0)

#replace NaN values with age_mean
df['age'] = df['age'].fillna(age_mean)
print(df['age'].isnull().sum())

0

In [26]:
# Calculate most frequency value of smoker 
df["smoker"].value_counts()
smoker_freq = df["smoker"].value_counts().idxmax()

In [27]:
# Replace it with NaN values
df["smoker"] = df["smoker"].fillna(smoker_freq)
df["smoker"].isnull().sum()

np.int64(0)